project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left:
      - text: Hands-on Exercises
        menu: 
          - text: Exercise 1 part 1 Data Wrangling with R
            href: Hands-on_Ex01/Hands-on_Ex1.html
          - text: Exercise 1 part 2 Choropleth Mapping with R
            href: Hands-on_Ex01/Hands-on_Ex1_part_2.html
      - text: In-class Exercises
        menu: 
          - text: In-class Exercise 1
            href: In-class_Ex/Ex1/In-class_Ex1.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: journal
    mainfont: calibri
    fontsize: 1.5rem
    
    css: styles.css
    toc: true

editor: visual

