project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left:
      - text: Hands-on Exercises
        menu: 
          - text: Ex 1 part 1 Data Wrangling with R
            href: Hands-on_Ex01/Hands-on_Ex1.html
          - text: Ex 1 part 2 Choropleth Mapping with R
            href: Hands-on_Ex01/Hands-on_Ex1_part_2.html
            
          - text: Ex 2 part 1 Spatial Weights & Applications
            href: Hands-on_Ex02/Hands-on_Ex2_1.html
          - text: Ex 2 part 2 Global Measures of Spatial Autocorrelation
            href: Hands-on_Ex02/Hands-on_Ex2_2.html
          - text: Ex 2 part 3 Local Measures of Spatial Autocorrelation
            href: Hands-on_Ex02/Hands-on_Ex2_3.html
            
      - text: In-class Exercises
        menu: 
          - text: In-class Exercise 1
            href: In-class_Ex/Ex1/In-class_Ex1.html
            
          - text: In-class Exercise 2 Spatial Weights
            href: In-class_Ex/Ex1/In-class_Ex2.html
          - text: In-class Exercise 2 GLSA 
            href: In-class_Ex/Ex1/In-class_Ex2_LISA.html
          - text: In-class Exercise 2 EHSA 
            href: In-class_Ex/Ex1/In-class_Ex2_EHSA.html
            
      - text: Take home Exercises
        menu: 
          - text: Take home Exercise 1
    right:
      - href: index.qmd
        text: Home
      - index.qmd

format:
  html:
    theme: sandstone
    
    css: styles.css
    toc: true

editor: visual

